name: mvna-asd
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
      - mne>=1.6.0
      - torch>=2.1.0
      - numpy
      - scikit-learn
      - pandas
      - tobii_research
